### ISSUE TITLE
MIssing case arms do not generate warnings, and cannot be made to generate them using a default: `_ -> warning "Missing arm" _`

### ISSUE THREAD

**Issue by rossc719g** [B-Lang-org/bsc#746] opened 2024-11-01 23:50 UTC
See:  https://github.com/rossc719g/bsc_examples/blob/main/missing_case_arm

TL;DR:

```bh
data ThreeOneTwo = Three | One | Two
  deriving (Bits, Eq)

interface MissingCaseArm =
  testCase :: ThreeOneTwo -> ActionValue (UInt 2)
```

This does not generate a warning (but definitely should):

```bh
mkMissingCaseArm :: Module MissingCaseArm
mkMissingCaseArm = module
  interface MissingCaseArm
    testCase x = return $ case x of
      One -> 1
      Two -> 2
      -- Missing arm for Three. Generated verilog will give 2'b0.
```

And you cannot trick the compiler into giving you a warning like this because it always generates the warning.
```bh
mkMissingCaseArmWarn :: Module MissingCaseArm
mkMissingCaseArmWarn = module
  interface MissingCaseArm
    testCase x = return $ case x of
      One -> 1
      Two -> 2
      Three -> 3
      -- No missing arm.
      _ -> warning "Missing arm!" _  -- Should be unreachable
```

**Comment by quark17** [comment] 2024-11-02 18:37
Sorry for asking you to file this, as I just realized that it's a duplicate of #226

**Closed** 2024-11-02 18:56 UTC
