### ISSUE TITLE
Add Toooba BSV RISC-V OoO processor to test suite

### ISSUE THREAD

**Issue by charlie-bluespec** [B-Lang-org/bsc#321] opened 2021-02-12 20:44 UTC
https://github.com/bluespec/Toooba

**Comment by quark17** [comment] 2021-03-30 01:27
With PR #342 merged (specifically commit 00185f79), BSC commits are now checked against Toooba.  This doesn't add Toooba to the testsuite (in the `testsuite` subdirectory); instead it adds a new job to GitHub CI that: checks out Toooba, builds the Bluesim model, and runs the default test.

At the moment the GitHub CI has one job for the testsuite, which means that results aren't available until the entire suite has finished (and if it fails, you don't immediately know where it failed).  It might be worth splitting the current testsuite job into separate jobs that run only certain subsets (such as just the `bsc.typechecker` directory, say), so that more results can be reported sooner, and separately.  (If we did that, maybe Toooba could be added to the testsuite, but still run as a separate job.)

The Toooba job only runs one tests, because the regression script in that repo has some issues that prevent using it in GitHub workflows.  The Toooba job is also only testing Bluesim, not the Verilog.  But what it's testing is still significant.  It is also run four times, for each of the Ubuntu and macOS environments -- this might be overkill, but it's good to test all the environments (and their different versions of tools and C/C++ compilers).  We might consider setting up our CI to only do some testing on every commit/PR and to do complete testing (of a large range of tool combinations) at regular intervals -- at the moment, we're only triggering jobs on commits/PR.

**Closed** 2023-08-24 10:01 UTC
